// List of fonts available for text customization in the design tool
export const fonts = [
  'Playfair Display',
  'Georgia',
  'Noto Serif Display',
  'Times New Roman',
  'DM Serif Display',
  'Lato',
  'Garamond',
  'Palatino',
  'Cursive',
  'Papyrus',
  'Lucida Calligraphy',
  'Brush Script MT',
  'Comic Sans MS',
  'Montserrat',
  'Russo One',
  'Anybody',
  'Boldonse',
  'Judson',
  'Mulish',
  'Space Mono',
  'UnifrakturMaguntia',
  'Mea Culpa',
  'Italianno',
  'Ballet',
  'Itim',
  'Roboto',
  'Caprasimo',
];
